CPU_ONLY := 1

BLAS := open

OPENCV_VERSION := 3

PYTHON_INCLUDE := /usr/include/python3.12 \
        /usr/local/lib/python3.13/dist-packages/numpy/core/include

PYTHON_LIB := /usr/lib/x86_64-linux-gnu

INCLUDE_DIRS := /usr/local/include \
                /usr/include/opencv4 \
                /usr/include/hdf5/serial

LIBRARY_DIRS := /usr/lib/x86_64-linux-gnu \
                /usr/lib/x86_64-linux-gnu/hdf5/serial

BUILD_DIR := build
DISTRIBUTE_DIR := distribute

TEST_GPUID := 0

Q ?= @
